### PR TITLE
Upgrade to jfreechart 1.5.0 and Clojure 1.9.0

### PR DESCRIPTION
**Pull request by marco-m**
NOTE: This is a breaking change, because jfreechart removed method createBarChart3D.
Accordingly, I propose to bump cljfreechart to 0.2.0

### CODE REVIEW

**Comment by kumarshantanu** [comment]
@marco-m Thanks for the patch! Is there any replacement for `createBarChart3D` in the new JFreeChart version?

**Comment by marco-m** [comment]
Hello @kumarshantanu,
the commit removing `createBarChart3D` is 1be317c64d, comment says `Remove deprecated code`. If you look at https://github.com/jfree/jfreechart, it says:

```
Migration from JFreeChart 1.0.x
...
all the classes relating to pseudo-3D charts have been removed, as much better 3D charts
are offered by Orson Charts so we prefer not to maintain the pseudo-3D chart code within 
JFreeChart;
```

Orson Charts is at https://github.com/jfree/orson-charts.

So in my understanding there is no replacement within JFreeChart itself.

**Comment by kumarshantanu** [comment]
@marco-m I've cut a release `0.2.0` with your change. Sorry about the long turnaround time!

**Comment by marco-m** [comment]
No problems! Thanks!

**Pull request merged**
